### ISSUE TITLE
attachments not copied to phpbb files folder

### ISSUE THREAD

**Issue by classofoutcasts** [camel1cz/phorum2phpbb#1]
Images are not copied to the attachments folder, they are imported into the attachments table.
I used the 'store files on disk' module to convert the phorum attachments (in database) to attachments on disk. Successfully tested, Phorum loaded the attachments from the folder after this conversion.

The phorum->phpbb conversion script successfully imported the files db table, but unfortunately did not copy the files to the 'files' folder in phpBB.

Any ideas why the images wheren't copied during the phorum5.2.9 - php3.0.5 conversion?

**Comment by camel1cz** [comment]
The data files was not meant to be copied... when I wrote this code, I was not aware, phorum can store files into DB. In my situation, the files was stored in folder. In my opinion it was less trouble to do the  copy manually.

Do you plan to enhance this code?

In the meantime I updated the description to clarify the attachments handling.

**Comment by classofoutcasts** [comment]
I'm now (as we speak) copying the files manually after running your script, wrote a small script which takes care of that last night. Enhancing the code would be a day job as I'm not familiar with the phorum api and phpbb structure.. Thanks for updating the description!

**Comment by camel1cz** [comment]
No problem and good luck!
